# Generated by Django 3.2.5 on 2021-07-22 14:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website', models.CharField(default=None, max_length=50)),
                ('image', models.CharField(default=None, max_length=50)),
                ('is_pets_allowed', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
