# Generated by Django 3.2.5 on 2021-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(default='Côte is inspired by the brasseries of Paris, championing relaxed all-day dining and serving authentic French classics made from great quality, fresh ingredients.', max_length=500),
            preserve_default=False,
        ),
    ]
