# Generated by Django 3.2.5 on 2021-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
