# Generated by Django 3.2.5 on 2021-07-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_categories_category'),
        ('places', '0002_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(related_name='place', to='categories.Category'),
        ),
    ]
