# Generated by Django 3.2.5 on 2021-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('places', '0003_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(default=True, null=True, related_name='places', to='categories.Category'),
        ),
    ]
